### ISSUE TITLE
alevin-fry quant fails bc of mismatch  in number of tx present vs number of tx in tg-map

### ISSUE THREAD

**Issue by vinay-swamy** [COMBINE-lab/alevin-fry#19] opened 2021-03-01 22:00 UTC
Hi, I was testing out alevin-fry and got up to the `quant` step, and got this error message
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `140992`,
 right: `141131`: The tg-map must contain a gene mapping for all transcripts in the header', libradicl/src/quant.rs:467:5
```
I'm using the same file for `--tg-map` that I used for `--tgMap` in my `salmon alevin` command. the tx in this file also match up to the fasta I used for my `salmon index` command.  I commented out the assertion causing the failure, rebuilt, and it ran okay. If I had to guess, the few transcripts that are removed for various reasons(too short?) during `salmon index` will be in my tg-map but not in the downstream data. Maybe change the assertion to fail only if there transcripts in the rad file that are not in the tg-map file

**Comment by rob-p** [comment] 2021-04-02 19:18
Hi @vinay-swamy,

  Thanks for reporting this issue.  Somehow, I'd not been notified from your initial posting of the issue so I apologize for taking so long to get back to you here.  I _think_ that short transcripts should still appear in the header (though I will check).  I wonder if the transcripts that were removed were sequence duplicates.  Would you get this error if you indexed with `--keepDuplicates`?

Thanks,
Rob

**Comment by rob-p** [comment] 2021-04-07 13:50
Hi @vinay-swamy,

  After some more testing, I'm fairly sure this is due to the use of an index with decoys in it during the generation of the RAD file.  When you have a chance, can you please confirm this?  We've further clarified in the documentation that this is not supported in the current alevin-fry pipeline.

Thanks,
Rob

**Comment by rob-p** [comment] 2021-04-21 04:29
Hi @vinay-swamy,

  After doing testing, I'm fairly certain this is the result of mapping upstream with decoy sequences in the index which isn't supported.  Nonetheless, we've just pushed v0.2.0 which has some otherwise nice new features and performance improvements.  I'm going to close this for now, but please feel free to reopen if you encounter this issue and it seems _not_ to be caused by decoys.

**Closed by rob-p** 2021-04-21 04:29 UTC

**Comment by AnnaAMonaco** [comment] 2023-10-18 08:27
Hi, sorry to re-open this but I have encountered the same error and I'm a bit at my wits' end. I also get the same issue at the `quant` step of alevin-fry (`salmon alevin`, `alevin-fry generate-permit-list`, and `alevin-fry collate` run smoothly).

Here's the last step with error message. Like vinay-swamy I used the same `--tg-map` here as the `--tgMap` in `salmon alevin`
```
$ alevin-fry quant -i $outDir --tg-map $tsv -t 30 -r cr-like -o $outDir
2023-10-17 14:57:08 INFO quantifying from uncompressed, collated RAD file File { fd: 4, path: "/project/MDL_monaco/analysis/04_scComparisons/04_ateAlb_musMus/02_musMus_soloRun/outs/mpimg_L29135-1_D1-D2-Mmu-E14-5_S5_L003/map.collated.rad", read: true, write: false }
2023-10-17 14:57:08 INFO paired : false, ref_count : 227,777, num_chunks : 123,914
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `227111`,
 right: `227777`: The tg-map must contain a gene mapping for all transcripts in the header', src/utils.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I first checked that the tsv and the fasta I used for the index had the same amount of transcripts, and that there were no "holes" in my tg-map:
```
$ wc -l $tsv
227777 
$ grep ">" mm10.GRCm38.txp.clean.fa | wc -l
227777

$ cut -f1 $tsv | wc -l
227777
$ cut -f2 $tsv | wc -l
227777
```

The transcript names are also in the same order between tsv and fasta headers (you never know). I just assigned the fasta to `file1` and the tsv to `file2` here.
```
$ grep ">" $file1 | head
>ENSMUST00000162897
>ENSMUST00000159265
>ENSMUST00000070533
>ENSMUST00000161581
>ENSMUST11000161581
>ENSMUST00000192692
>ENSMUST00000194643
>ENSMUST00000192427
>ENSMUST11000194643
>ENSMUST11000192427
$ head $file2
ENSMUST00000162897      Xkr4
ENSMUST00000159265      Xkr4
ENSMUST00000070533      Xkr4
ENSMUST00000161581      Gm1992
ENSMUST11000161581      Gm1992
ENSMUST00000192692      Gm19938
ENSMUST00000194643      Gm37381
ENSMUST00000192427      Gm37381
ENSMUST11000194643      Gm37381
```

So I tried to find those 666 (ha) lines that are not in both files, but that didn't work out: it just spits back all the lines one by one (I don't vouch for my "seeker" code, could be absolute rubbish).
```
$ while IFS= read -r line; do
>     if [[ $line =~ \>(.*) ]]; then
>         substring="${BASH_REMATCH[1]}"
>         found_match=0
>
>         for item in "${file2_array[@]}"; do
>             if [[ "$item" == "$substring" ]]; then
>                 found_match=1
>                 break
>             fi
>         done
>
>         if [ "$found_match" -eq 0 ]; then
>             echo "No match found in File2 for: $substring"
>         fi
>     fi
> done < "$file1"
No match found in File2 for: ENSMUST00000162897
No match found in File2 for: ENSMUST00000159265
No match found in File2 for: ENSMUST00000070533
No match found in File2 for: ENSMUST00000161581
No match found in File2 for: ENSMUST11000161581
No match found in File2 for: ENSMUST00000192692
No match found in File2 for: ENSMUST00000194643
No match found in File2 for: ENSMUST00000192427
^C
```
I also made a brand new index for this quantification, in the past I had an incompatibility with using an index made with an older version of `salmon`, so this is not the case here.

Any help or troubleshooting tips are strongly appreciated!

**Comment by rob-p** [comment] 2023-10-18 11:22
Cc @DongzeHE.

**Comment by rob-p** [comment] 2023-10-19 13:00
Hi @AnnaAMonaco,

  First, sorry you are seeing this frustrating issue. Hopefully, its its something simple but subtle. Is there any portion of this data you could share to help us debug? Specifically, the rad, reference and t2g files would be the most useful.

Thanks!
Rob

**Comment by AnnaAMonaco** [comment] 2023-10-19 13:11
@rob-p, thank you for the offer!

Would the first unique 100 transcripts from the rad file + corresponding txp.fasta and tgMap suffice?

**Comment by rob-p** [comment] 2023-10-19 13:32
As long as that triggers the error, for sure!

--Rob
